<?php
$title = 'Employee Register';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if (!empty($id))
	$form->setAttribute('action', $this->url('employee/default', array('controller' => 'employee','action' => 'add','id'=>$id,'page' => $pageNumber)));
else 
	$form->setAttribute('action', $this->url('employee/default', array('controller' => 'employee','action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div id="empId">
	<label class="popup_textfields"><?php echo strip_tags($this->formlabel($form->get('empId')),'<label>');?></label>
	<?php echo $this->formelement($form->get('empId'));?>
	<span class="error-msg" id="empId_lbl"><?php echo $this->formElementErrors($form->get('empId'));?></span>
</div>
<?php if ($formName == 'add') :?>
<div id="empPass">
	<label class="popup_textfields"><?php echo strip_tags($this->formlabel($form->get('empPass')),'<label>');?></label>
	<?php echo $this->formelement($form->get('empPass'));?>
	<span class="error-msg" id="empPass_lbl"><?php echo $this->formElementErrors($form->get('empPass'));?></span>
</div>
<div id="empConfirmPass">
	<label class="popup_textfields"><?php echo strip_tags($this->formlabel($form->get('empConfirmPass')),'<label>');?></label>
	<?php echo $this->formelement($form->get('empConfirmPass'));?>
	<span class="error-msg" id="empConfirmPass_lbl"><?php echo $this->formElementErrors($form->get('empConfirmPass'));?></span>
</div>
<?php endif;?>
<div id="empEmail">
	<label class="popup_textfields"><?php echo strip_tags($this->formlabel($form->get('empEmail')),'<label>');?></label>
	<?php echo $this->formelement($form->get('empEmail'));?>
	<span class="error-msg" id="empEmail_lbl"><?php echo $this->formElementErrors($form->get('empEmail'));?></span>
</div>
<div id="empRole">
	<label class="popup_textfields"><?php echo strip_tags($this->formlabel($form->get('empRole')),'<label>');?></label>
	<?php echo $this->formelement($form->get('empRole'));?>
	<span class="error-msg" id="empRole_lbl"><?php echo $this->formElementErrors($form->get('empRole'));?></span>
</div>
<div id="submita">
<?php echo $this->formSubmit($form->get('submitbutton'));?>
</div>
<?php
echo $this->form()->closeTag();
?>