<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Employee Management Login')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/default.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
	<?php
	//layout.phtml
	//First get the viewmodel and all its children (ie the actions viewmodel)
	$children = $this->viewModel()
	                 ->getCurrent()
	                 ->getChildren();
	
	$ourView  = $children[0];
	if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
	<div class="flashMessages">
	    <?php foreach ($ourView->flashMessages as $fMessage) : ?>
	    <?php echo $fMessage; endforeach;?>
	</div>
	<?php endif; ?>
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">                
                <div class="collapse navbar-collapse">                    
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('login/default', array('controller' => 'index','action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('employee/default', array('controller' => 'employee','action' => 'add')) ?>"><?php echo $this->translate('Register') ?></a></li>
                    </ul>
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2006 - <?php echo date('Y') ?> by OSSCube Solutions Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
