<div class="jumbotron">
    <?php echo sprintf($this->translate('Welcome to %sEmployee Management System%s'), '<span class="zf-green">', '</span>') ?>    
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Employee Personal Details') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('This is for testing') ?></p>                
            </div>
        </div>
    </div>    
</div>
